### ISSUE TITLE
Implement spread mode [duplicate]

### ISSUE THREAD

**Issue by ReallyNecessarySherbert** [fechan/SIGILS#36]
I think it would be great to have a tutorial on adding custom nodes. For example, a node that can pull or put items into a specific slot of an inventory.

**Comment by ReallyNecessarySherbert** [comment]
I think it could be done by adding some low level nodes or maybe even module system.

**Comment by ReallyNecessarySherbert** [comment]
And if you want I may help you with that but I never worked with react-flow(only tried) but I worked with rete js(and even have few projects based on it).

**Comment by fechan** [comment]
Are you trying to pull a one or more slots out of an inventory so you can pipe items to those slots specifically? If so, it is already possible, but I have neglected to document it.

To separate a slot, click and drag the slot outside of its slot group. This will make a new slot group with just that slot. For separating multiple slots, right now you can't separate multiple slots at a time, so you'll have to do the tedious process of separating out slots one-by-one, then dragging the slot groups together. That could definitely be improved.

PRs are welcome, and let me know if you have any questions.

**Comment by ReallyNecessarySherbert** [comment]
And I think it would be good if there was some node for math and node for taking only a specific amount of items. It may allow mass smelting as well.

**Comment by ReallyNecessarySherbert** [comment]
Can you please show which part of code is used for handling nodes(I mean adding(In computer craft as well)) and how they are being handled Inside of computer craft then I may try to implement it by myself(If you don't mind).

**Comment by ReallyNecessarySherbert** [comment]
(I would try to implement module system as well)

**Comment by fechan** [comment]
> Can you please show which part of code is used for handling nodes(I mean adding(In computer craft as well)) and how they are being handled Inside of computer craft then I may try to implement it by myself(If you don't mind).

Don't implement item spread as a property of the node, as it would add unnecessary complexity to the code. Even fluid tanks and regular items slots are the same type of node, just with an extra property denoting whether it holds fluids.

Instead, I started abstracting item and fluid behavior out to [pipeModes](https://github.com/fechan/SIGILS/tree/master/computercraft/sigils/pipeModes). At the moment, it automatically selects the "fluid" mode if the edge connects two fluids, but it should be easy to implement a selector for different pipe modes like "natural" (the default) and "spread" in the editor, and have that passed down to the ComputerCraft side.

I actually started implementing a spread mode before I stopped working on this, but I haven't committed it yet. I'll make a branch, and maybe you can take a look.

**Comment by fechan** [comment]
Here it is https://github.com/fechan/SIGILS/pull/37/files

> (I would try to implement module system as well)

What do you mean by module system? This feels like this should be in a different issue, and discussed before it is implemented.

**Comment by fechan** [comment]
By the way, [here's the ComputerCraft function](https://github.com/fechan/SIGILS/blob/5d8a5ad3253e5c15a6bf2ca52d410370d5e8c224/computercraft/sigils/pipe.lua#L40) that processes a given pipe. This is where the pipeMode function to be used is selected .

**Comment by fechan** [comment]
Oh, I forgot I made an issue for the spread mode specifically too https://github.com/fechan/SIGILS/issues/35

**Comment by ReallyNecessarySherbert** [comment]
Thanks but I don't get why here is used not not -   return not not (
    peripheral.size and
    (string.find(periphId, 'minecraft:chest_') or

**Comment by fechan** [comment]
> Thanks but I don't get why here is used not not - return not not ( peripheral.size and (string.find(periphId, 'minecraft:chest_') or

That is a hacky way to make sure the return type is boolean, since peripheral.size is a number.

Regardless, I have to stress **you do not and should not** need to add new node types to implement the spread mode.

Please move the discussion on spread mode implementation to #35, and make a new issue to discuss your module system.
